name: Download Qt SDK

on:
  workflow_dispatch:

jobs:
  qt-sdk:
    runs-on: ubuntu-22.04

    env:
      QT_VERSION: 6.8.0

    steps:
      - name: Install Python
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip

      - name: Install aqtinstall
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install aqtinstall

      - name: Download Qt SDK
        uses: jurplel/install-qt-action@v4
        with:
          version: '${QT_VERSION}'
          dir: '${{ github.workspace }}/Qt/'

      - name: Verify Qt
        run: |
          find ${{ github.workspace }}/Qt

      - name: Pack SDK
        run: |
          cd ${{ github.workspace }}
          tar czf qt-${QT_VERSION}-linux.tar.gz Qt

      - name: Upload SDK
        uses: actions/upload-artifact@v4
        with:
          name: qt-sdk-linux-gcc64
          path: ${{ github.workspace }}/qt-${{ env.QT_VERSION }}-linux.tar.gz
